# Cloud Build configuration for Alex AI Assistant
# Triggers on push to main branch

steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/alex:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/alex:latest'
      - '-f'
      - 'infrastructure/Dockerfile'
      - '.'

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/alex:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/alex:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'alex'
      - '--image=gcr.io/$PROJECT_ID/alex:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-secrets=NEO4J_URI=neo4j-uri:latest,NEO4J_PASSWORD=neo4j-password:latest,GOOGLE_API_KEY=google-api-key:latest'
      - '--max-instances=5'
      - '--min-instances=0'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--timeout=300'
      - '--concurrency=80'

images:
  - 'gcr.io/$PROJECT_ID/alex:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/alex:latest'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'
